<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->toHtml() ?></div>

<div class="row product-wrapper">
    <div class="col-md-6">
        <div class="row">
            <?php echo $this->getChildHtml('media') ?>
        </div>
    </div>
    <div class="col-md-4 product-information">
        <h1 class="product-name">
            <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
        </h1>

        <h1 class="red-color product-price">
            <?php echo $this->getPriceHtml($_product) ?>
        </h1>
        <?php if ($_product->getDescription()):?>
        <p class="product-description">
            <div>
                <?php echo $_helper->productAttribute($_product, nl2br($_product->getDescription()), 'description'); ?>
            </div>
        </p>
        <?php endif;?>

        <?php if($_product->isSaleable()): ?>
        <form class="product-add-to-cart" action="<?php echo $this->getSubmitUrl($_product, array('_secure' => $this->_isSecure())) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
            <?php echo $this->getChildHtml('addtocart') ?>
        </form>
        <script type="text/javascript">
                //<![CDATA[
                var productAddToCartForm = new VarienForm('product_addtocart_form');
                productAddToCartForm.submit = function(button, url) {
                    if (this.validator.validate()) {
                        var form = this.form;
                        var oldUrl = form.action;

                        if (url) {
                            form.action = url;
                        }
                        var e = null;
                        try {
                            this.form.submit();
                        } catch (e) {
                        }
                        this.form.action = oldUrl;
                        if (e) {
                            throw e;
                        }

                        if (button && button != 'undefined') {
                            button.disabled = true;
                        }
                    }
                }.bind(productAddToCartForm);

                productAddToCartForm.submitLight = function(button, url){
                    if(this.validator) {
                        var nv = Validation.methods;
                        delete Validation.methods['required-entry'];
                        delete Validation.methods['validate-one-required'];
                        delete Validation.methods['validate-one-required-by-name'];
                        // Remove custom datetime validators
                        for (var methodName in Validation.methods) {
                            if (methodName.match(/^validate-datetime-.*/i)) {
                                delete Validation.methods[methodName];
                            }
                        }

                        if (this.validator.validate()) {
                            if (url) {
                                this.form.action = url;
                            }
                            this.form.submit();
                        }
                        Object.extend(Validation.methods, nv);
                    }
                }.bind(productAddToCartForm);
                //]]>
    </script>
        <?php endif; ?>

        <button type="button" class="btn modal-opener" data-modal-open="#product-personalize">
            <span><img src="<?php echo $this->getSkinUrl('assets/img/edit.png'); ?>"/> Personalizza </span>
        </button>

        <ul class="product-additional">
            <li>
                <span class="title">Details <i class="icon-caret-down red-color"></i> </span>
                <p>
                    Some info here
                </p>
            </li>
            <li>
                <span class="title">Shipping <i class="icon-caret-down red-color"></i> </span>
                <p>
                    Some info here
                </p>
            </li>
            <li>
                <span class="title">Returns <i class="icon-caret-down red-color"></i> </span>
                <p>
                    Some info here
                </p>
            </li>
        </ul>
        <div class="social-links">
            <span><i class="icon-facebook"></i></span>
            <span><i class="icon-twitter"></i></span>
            <span><i class="icon-pinterest"></i></span>
        </div>
    </div>
</div>

<?php echo $this->getChildHtml('modal'); ?>

<?php echo $this->getChildHtml('related'); ?>