
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
    <?php echo $this->getChildHtml('head') ?>
</head>
<body>
<?php echo $this->getChildHtml('header') ?>
<section class="bg-gray">
    <?php echo $this->getChildHtml('breadcrumbs') ?>
    <div class="container" style="margin-top: 30px; padding-bottom: 122px">
        <?php echo $this->getChildHtml('content'); ?>
    </div>
</section>

<?php echo $this->getChildHtml('footer') ?>
</body>
</html>

<script src="https://unpkg.com/babel-standalone@6/babel.min.js"></script>

