<?php $_product = $this->getProduct(); ?>
<?php $buttonTitle = $this->__('Add to Cart'); ?>
<?php if($_product->isSaleable()): ?>
    <?php if(!$_product->isGrouped()): ?>
        <label for="qty" class="text-uppercase"><?php echo $this->__('Qty:') ?></label>
        <input type="text" name="qty" id="qty" maxlength="12" value="<?php echo $this->getProductDefaultQty() * 1 ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Qty')) ?>" class="input-text qty" />
    <?php endif; ?>
    <button type="button" title="<?php echo $buttonTitle ?>" id="product-addtocart-button" class="button btn btn-success btn-cart" onclick="productAddToCartForm.submit(this)"><span><span><?php echo $buttonTitle ?></span><i class="icon-light-right"></i></span></button>
    <?php echo $this->getChildHtml('', true, true) ?>
<?php endif; ?>
