<?php
$_product = $this->getProduct();
$_helper = $this->helper('catalog/output');
?>
<div class="modal-wrapper" id="product-personalize">
    <div class="modal-bg modal-closer" data-modal-close="#product-personalize"></div>
    <div class="modal-body">
        <div class="row content-center">
            <h4 class="modal-heading">
                <span>Taccuino Maxi A Righe</span>
            </h4>
        </div>
        <div class="row modal-product-wrapper items-center">
            <div class="col-md-6">
            <?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
                <div class="product-preview">
                    <?php
                    $_img = '<img id="image" src="'.$this->helper('catalog/image')->init($_product, 'image').'" alt="'.$this->escapeHtml($this->getImageLabel()).'" title="'.$this->escapeHtml($this->getImageLabel()).'" />';
                    echo $_helper->productAttribute($_product, $_img, 'image');
                    ?>
                </div>
            <?php endif; ?>
            </div>
            <form class="col-md-6 product-customise-form">
                <div class="form-group">
                    <label>
                            <span>
                                Inserisci il testo
                            </span>
                    </label>
                    <p class="tip-label" style="margin: 10px 0">
                            <span>
                                Max 20 caratteri
                            </span>
                    </p>
                    <input type="text" class="bordered" name="text" placeholder="Nome Cognome">
                    <p class="tip-label" style="text-align: right;margin: 5px 4px 9px;">
                        <span>11/20</span>
                    </p>
                    <input type="text" class="bordered bg-gray" placeholder="">
                </div>
                <div class="form-group">
                    <p class="label-container">
                        <label>Scegli il colore: </label>
                        <span><strong>Rosso</strong></span>
                    </p>
                    <input type="hidden" name="color" value="Rosso">
                    <div class="block-list">
                        <div class="block-container">
                            <div class="block" style="background-color: #ff1e00"></div>
                            <p class="tip-label">Rosso</p>
                        </div>
                        <div class="block-container">
                            <div class="block" style="background-color: #0069b4"></div>
                            <p class="tip-label">Blu</p>
                        </div>
                        <div class="block-container">
                            <div class="block" style="background-color: #db8f01"></div>
                            <p class="tip-label">Oro</p>
                        </div>
                        <div class="block-container">
                            <div class="block bordered" style="background-color: #dadada"></div>
                            <p class="tip-label">Argento</p>
                        </div>
                        <div class="block-container">
                            <div class="block" style="background-color: #000000"></div>
                            <p class="tip-label">Nero</p>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <p class="label-container">
                        <label>Scegli Font: </label>
                        <span><strong>Sans</strong></span>
                        <input type="hidden" name="font" value="sans">
                    </p>
                    <div class="block-list font-block-list">
                        <div class="block-container">
                            <img src="<?php echo $this->getSkinUrl('assets/img/sans.jpg'); ?>" class="block active" alt="sans">
                            <p class="tip-label sans">Sans</p>
                        </div>
                        <div class="block-container">
                            <img src="<?php echo $this->getSkinUrl('assets/img/serif.jpg'); ?>" class="block" alt="serif">
                            <p class="tip-label serif">Serif</p>
                        </div>
                    </div>
                </div>

                <h1 class="red-color product-price" style="margin: -10px 0 6px 0px;">
                    € 16.90
                </h1>
                <p>
                    + € 5.00 personalizzazione
                </p>

                <div class="product-add-to-cart">
                    <label class="gray-color">QT.</label>
                    <input type="number" value="1">
                </div>

                <button type="submit" class="btn btn-success">
                    <span>Conferma E Aggiungi Al Carello</span>
                </button>
            </form>
        </div>
        <p class="row modal-warning-tip">
            Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta
        </p>
        <div class="modal-cancel modal-closer" data-modal-close="#product-personalize">
            <svg height="14px" viewBox="0 0 174.239 174.239">
                <path d="M146.537,1.047c-1.396-1.396-3.681-1.396-5.077,0L89.658,52.849c-1.396,1.396-3.681,1.396-5.077,0L32.78,1.047 c-1.396-1.396-3.681-1.396-5.077,0L1.047,27.702c-1.396,1.396-1.396,3.681,0,5.077l51.802,51.802c1.396,1.396,1.396,3.681,0,5.077 L1.047,141.46c-1.396,1.396-1.396,3.681,0,5.077l26.655,26.655c1.396,1.396,3.681,1.396,5.077,0l51.802-51.802 c1.396-1.396,3.681-1.396,5.077,0l51.801,51.801c1.396,1.396,3.681,1.396,5.077,0l26.655-26.655c1.396-1.396,1.396-3.681,0-5.077 l-51.801-51.801c-1.396-1.396-1.396-3.681,0-5.077l51.801-51.801c1.396-1.396,1.396-3.681,0-5.077L146.537,1.047z"></path>
            </svg>
        </div>
    </div>
</div>