<?php if($crumbs && is_array($crumbs)): ?>
    <div class="container">
        <div class="row items-center content-between" style="height: 50px;">
            <ul class="breadcrumbs">
                <?php foreach($crumbs as $_crumbName=>$_crumbInfo): ?>
                <li class="<?php echo $_crumbName ?>">
                    <?php if($_crumbInfo['link']): ?>
                    <a href="<?php echo $_crumbInfo['link'] ?>" title="<?php echo $this->htmlEscape($_crumbInfo['title']) ?>">
                        <span><?php echo $this->htmlEscape($_crumbInfo['label']) ?></span>
                    </a>
                    <?php else: ?>
                    <a>
                        <span><?php echo $this->htmlEscape($_crumbInfo['label']) ?></span>
                    </a>
                    <?php endif; ?>
                </li>
                <?php endforeach; ?>
            </ul>
            <div class="back-button">
                <a href="<?php echo Mage::helper('core/http')->getHttpReferer() ? Mage::helper('core/http')->getHttpReferer()  : Mage::getUrl(); ?>">
                    <span>Back</span>
                </a>
            </div>
        </div>
    </div>
<?php endif; ?>