<section>
    <div class="row socials-wrapper">
        <div class="col-md-6 bg-black-light row items-center">
            <div class="col-md-12">
                <div class="container-half container-half-left">
                    <div class="content subscribe-form">
                        <h3 class="heading">
                            <span>Newsletter</span>
                        </h3>
                        <p class="paragraph">
                            Promo e novità dal mondo Legami.<br>
                            Ricevi subito il 10% di sconto sul tuo primo ordine!
                        </p>
                        <form>
                            <div class="input-text-wrapper">
                                <input class="with-button" type="text" placeholder="Enter your email address"/>
                                <button type="submit">
                                    <span>
                                        <img src="<?php echo $this->getSkinUrl('assets/img/arrow.svg'); ?>" alt="➜">
                                    </span>
                                </button>
                            </div>
                            <div class="input-checkbox-wrapper">
                                <input id="privacy-policy" type="checkbox">
                                <label for="privacy-policy">
                                    <div class="checkbox-fake"></div>
                                    <span>I read the privacy policy--</span>
                                </label>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6 bg-red row items-center">
            <div class="col-md-12">
                <div class="container-half container-half-right">
                    <div class="content">
                        <h3 class="heading">
                            <span>Seguici Sui Social</span>
                        </h3>
                        <p class="social-links row items-center content-center" >
                            <a href="#">
                                <span>
                                    <i class="icon-facebook"></i>
                                </span>
                            </a>
                            <a href="#">
                                <span>
                                    <i class="icon-twitter"></i>
                                </span>
                            </a>
                            <a href="#">
                                <span>
                                    <i class="icon-pinterest"></i>
                                </span>
                            </a>
                            <a href="#">
                                <span>
                                    <i class="icon-instagram"></i>
                                </span>
                            </a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="gray-links">
        <div class="row">
            <div class="col-md-4 column">
                <div class="row">
                    <div class="image-container">
                        <img src="<?php echo $this->getSkinUrl('assets/img/img11.png'); ?>" alt="rocket.png">
                    </div>
                    <ul>
                        <li>
                            <a href="#">
                                <span>About Us</span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span>Ethical Code</span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span>Legami For Life</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-4 column">
                <div class="row">
                    <div class="image-container">
                        <img src="<?php echo $this->getSkinUrl('assets/img/img12.png'); ?>" alt="rocket.png">
                    </div>
                    <ul>
                        <li>
                            <a href="#">
                                <span>Lavora Con Noi</span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span>Special for businesses</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-4 column">
                <div class="row">
                    <div class="image-container">
                        <img src="<?php echo $this->getSkinUrl('assets/img/img13.png'); ?>" alt="rocket.png">
                    </div>
                    <ul>
                        <li>
                            <a href="#">
                                <span>Contattaci</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>